# Generated by Django 3.2.9 on 2021-11-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='refid',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
