# Generated by Django 3.2.9 on 2021-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyseries', '0002_auto_20211121_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('feedback', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
