# Generated by Django 3.2.9 on 2021-11-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyseries', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msgid',
            new_name='refid',
        ),
    ]
