# Generated by Django 3.2.9 on 2021-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyseries', '0004_rename_msgid_comment_refid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.CharField(default='', max_length=9000),
        ),
    ]
